### ISSUE TITLE
alt_3prime events AssertionError 

### ISSUE THREAD

**Issue by paulojannig** [ratschlab/spladder#149]
* spladder version: 3.0.0
* Python version: 3.9.5
* Operating System: Ubuntu 20.04.3 LTS

### Description

Hello! I've run spladder build with several bam and annotation files, including the ones you provide as example (STAR.bam 5M and gencode gtf files), and I'm always getting the same Assertion error. I've read the closed "Assertion Error" issues, which helped me on updating the spladder version, but I'm still ending up with the same error.

### What I Did

`spladder build -o spladder_out_1000 -b STAR.bam -a gencode.v19.annotation.mult_iso_subsample_1000_genes.gtf`

Error:
```
Reporting confirmed alt_3prime events:
writing alt_3prime events in gff3 format to spladder_out_1000/merge_graphs_alt_3prime_C3.confirmed.gff3
Traceback (most recent call last):
  File "/home/paujan/miniconda3/bin/spladder", line 33, in <module>
    sys.exit(load_entry_point('spladder==3.0.0', 'console_scripts', 'spladder')())
  File "/home/paujan/miniconda3/lib/python3.9/site-packages/spladder/spladder.py", line 229, in main
    options.func(options)
  File "/home/paujan/miniconda3/lib/python3.9/site-packages/spladder/spladder_build.py", line 163, in spladder
    analyze_events(event_type, options.bam_fnames, options)
  File "/home/paujan/miniconda3/lib/python3.9/site-packages/spladder/alt_splice/analyze.py", line 185, in analyze_events
    write_events_gff3(fn_out_conf_gff3, events_all, confirmed_idx)
  File "/home/paujan/miniconda3/lib/python3.9/site-packages/spladder/alt_splice/write.py", line 328, in write_events_gff3
    assert(np.sum(ev.exons1[:, 1] - ev.exons1[:, 0]) <= np.sum(ev.exons2[:, 1] - ev.exons2[:, 0]))
AssertionError
```

Thanks a lot for you help in advance!

Cheers,
Paulo

**Comment by akahles** [comment]
Dear Paulo,

thank you very much for reporting. I have difficulties reproducing the error, which makes it very hard to debug. Would you be able to share the data you are running this / observing this on?

Thanks and Cheers,

Andre

**Comment by paulojannig** [comment]
Dear Andre,

Thanks for the fast reply.

I downloaded the files from your website, but had the same issue with my own bam files and mouse ensembl annotation.
[**STAR.bam**](https://public.bmi.inf.ethz.ch/projects/2015/spladder/alignments/5000000_reads/STAR.bam)
[**STAR.bam.bai**](https://public.bmi.inf.ethz.ch/projects/2015/spladder/alignments/5000000_reads/STAR.bam.bai)
[** gencode.v19.annotation.mult_iso_subsample_1000_genes.gtf**](https://public.bmi.inf.ethz.ch/projects/2015/spladder/annotation/gencode.v19.annotation.mult_iso_subsample_1000_genes.gtf)

Cheers,
Paulo

**Comment by akahles** [comment]
Thanks a lot for pointing me again to this dataset. I was able to reproduce the issue and fixed the bug. It only occurred when the alternative exons of an alt3p/alt5p event were differing in both exon coordinates. In this case, SplAdder trims to the end closer to the intron. However, this can change isoform-length order, later violating the check for a convention. 
The issue is fixed in the `development` branch and will soon be part of release version 3.0.1.

Cheers,
Andre

**Comment by akahles** [comment]
Hi Paulo,

I have now released version 3.0.1 on GitHub and PyPi. Please give it a go and see whether it solves your problem.

Cheers,

Andre

**Comment by paulojannig** [comment]
Hi Andre,
Thanks a lot! It did solve the problem :)
Cheers,
Paulo

**Comment by paulojannig** [comment]
Sorry for reopening this issue, just realised that the problem remains.
It went through before because I ran the command on top of an existing spladder_out folder, but then the resulting gff3 fils were incomplete (stopping at chr1, when the first error occurred I assume)

```
Reporting confirmed alt_3prime events:
writing alt_3prime events in gff3 format to spladder_out_1000/merge_graphs_alt_3prime_C3.confirmed.gff3
Traceback (most recent call last):
  File "/home/paujan/miniconda3/bin/spladder", line 33, in <module>
    sys.exit(load_entry_point('spladder==3.0.1', 'console_scripts', 'spladder')())
  File "/home/paujan/miniconda3/lib/python3.9/site-packages/spladder/spladder.py", line 229, in main
    options.func(options)
  File "/home/paujan/miniconda3/lib/python3.9/site-packages/spladder/spladder_build.py", line 163, in spladder
    analyze_events(event_type, options.bam_fnames, options)
  File "/home/paujan/miniconda3/lib/python3.9/site-packages/spladder/alt_splice/analyze.py", line 185, in analyze_events
    write_events_gff3(fn_out_conf_gff3, events_all, confirmed_idx)
  File "/home/paujan/miniconda3/lib/python3.9/site-packages/spladder/alt_splice/write.py", line 328, in write_events_gff3
    assert(np.sum(ev.exons1[:, 1] - ev.exons1[:, 0]) <= np.sum(ev.exons2[:, 1] - ev.exons2[:, 0]))
AssertionError
```

**Comment by akahles** [comment]
Are you using the same inputs as before? If yes, can you please try again from a clean output directory? SplAdder will re-use some of the previous output if it is already present at the output location. 

When trying a full run on a clean output directory using the data you provided above, it runs fine for me without problems.

Cheers,

Andre

**Comment by paulojannig** [comment]
Thanks Andre! It's working now :)
