### ISSUE TITLE
viz gives error 

### ISSUE THREAD

**Issue by NextGenSeek** [ratschlab/spladder#204]
* Python version: Python 3.10.13
* Operating System: Mac

### Description

After running spladder build and spladder test without errors, I used spladder viz and ran into an error. I tried different viz options, but same error, see below. Could you please help me solving this issue?

### What I Did
```
spladder viz --track coverage file1.bam, file2.bam --outdir direction
spladder viz --track splicegraph gene1 --outdir direction
```

Traceback (most recent call last):
  File "/path/to/anaconda3/lib/python3.10/site-packages/scipy/__init__.py", line 137, in __getattr__
    return globals()[name]
KeyError: 'array'

During handling of the above exception, another exception occurred:
  File "/path/to/anaconda3/bin/spladder", line 8, in <module>
    sys.exit(main())
  File "/path/to/anaconda3/lib/python3.10/site-packages/spladder/spladder.py", line 229, in main
    options.func(options)
  File "/path/to/anaconda3/lib/python3.10/site-packages/spladder/spladder_viz.py", line 210, in spladder_viz
    all_gene_names = get_gene_names(options.outdir, options.confidence, options.validate_sg, options.verbose)
  File "/path/to/anaconda3/lib/python3.10/site-packages/spladder/helpers_viz.py", line 37, in get_gene_names
    gene_names = sp.array([x.name.split('.')[0] for x in tmp_genes])
  File "/path/to/anaconda3/lib/python3.10/site-packages/scipy/__init__.py", line 139, in __getattr__
    raise AttributeError(
AttributeError: Module 'scipy' has no attribute 'array'

**Comment by akahles** [comment]
Thanks for reporting. This was caused by an old scipy dependency. I fixed it in the `development` branch. Should be available with the next release in the coming days.

**Comment by Midreancgle** [comment]
Hello
I have also encountered the same problem, when will the new version be released to fix this problem?@akahles 
Expect a quick fix.
Thanks!

**Comment by ADvorkinGheva** [comment]
I am using SplAdder 3.1.0 and am still experiencing the same issue - same error messages.

**Comment by akahles** [comment]
Should be addressed now in release 3.1.1
