### ISSUE TITLE
spladder.py (v1.0.0): GFF start coordinates off by -1 base

### ISSUE THREAD

**Issue by rschulzUK** [ratschlab/spladder#36]
Have attached a UCSC screenshot to illustrate. In the case shown, the DNA sequence contains two canonical AG splice acceptor sites in tandem. Spladder finds evidence for the use of both, based on the exon_skip GFF output, but in both cases, the start coordinate of the GFF feature is off by -1 base.

This happens irrespective of the strand from which the gene is transcribed, and the GFF end coordinates appear to be correct.

[gffStartOffBy-1Base.pdf.zip](https://github.com/ratschlab/spladder/files/270594/gffStartOffBy-1Base.pdf.zip)

**Comment by akahles** [comment]
Thanks for spotting this! I could swear I fixed that before, but the change must have gotten lost in another branch. 

Cheers,
Andre

**Comment by ajw2329** [comment]
Hello - 

I'm adding to this thread to report that this still appears to be an issue in the python version (I cloned a few weeks ago) in my output.  Please let me know if you need any examples.

thanks again for such a great tool!
